CUDA is not available. Using CPU instead.
{'name': 'ProcessedDataset', 'path': 'data/Yelp_pro/1', 'device': device(type='cpu'), 'split_ratio': [0.7, 0.1, 0.2], 'min_inter': 10, 'n_groups': 10, 'gamma': 1.552}
init dataset ProcessedDataset
Traceback (most recent call last):
  File "/Users/lucas/IPL/run.py", line 105, in <module>
    main()
  File "/Users/lucas/IPL/run.py", line 71, in main
    dataset = get_dataset(dataset_config)
  File "/Users/lucas/IPL/dataset.py", line 12, in get_dataset
    dataset = dataset(config)
  File "/Users/lucas/IPL/dataset.py", line 178, in __init__
    self.train_data = self.read_data(os.path.join(dataset_config['path'], 'train.txt'))
  File "/Users/lucas/IPL/dataset.py", line 200, in read_data
    with open(file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/Yelp_pro/1/train.txt'
